version: "3.8"
services:
  app:
    build: .
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    hostname: ${REDIS_HOST}
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    volumes:
      - ./_volume/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./_volume/redis/data:/root/redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5